### ISSUE TITLE
Wrong animation

### ISSUE THREAD

**Issue by rmasoni** [PhilippeKr/TorchLight#10]
The option `3 - Pulsating White` for the Light Spell actually has the swirl animation.

**Comment by PhilippeKr** [comment]
I call it pulsating, but it's actually the one called "Mysterious Emanation" in the interface. I thought "pulsating" was better, but I'm happy to change to another wording if you suggest one.

**Comment by rmasoni** [comment]
Perhaps something like “swirling stripes”, but it'd be great if you could add the actual “pulse” one as it makes sense for the Light spell.

**Comment by PhilippeKr** [comment]
OK, it will be done in the next version, in a few minutes hopefully.
