### ISSUE TITLE
Suggestion: Button Title Text

### ISSUE THREAD

**Issue by paullessing** [PhilippeKr/TorchLight#11]
Just installed the module and I love it - great work!

One suggestion I would have: Could you add title text to the buttons? When I first tried to use it it wasn't clear to me what each button does, and adding a `title` text (which would show on hover) would really help me. Something like:

```js
		let tbuttonLight   = $(`<div class="control-icon torchlight" title="Toggle Light Spell"><i class="fas fa-sun"></i></div>`);
		let tbuttonLantern = $(`<div class="control-icon torchlight" title="Toggle Lantern"><i class="fas fa-lightbulb"></i></div>`);
		let tbuttonTorch   = $(`<div class="control-icon torchlight" title="Toggle Torch"><i class="fas fa-fire"></i></div>`);
```

I would create a pull request for these suggestions but I don't know how the localisation works. I'm happy to make these changes myself if you could tell me how to localise them!

**Comment by deraviin** [comment]
I would like to second adding somewhere which button applies what, I actually came here to see what icons represent what lights but it's not listed here either haha... I love this module though! It's going to make things much easier for my player who doesn't have darkvision when everyone tries to rush off while he can't move waiting for me to set up his light spell.

**Comment by PhilippeKr** [comment]
Thanks for the suggestion and the implementation, it should be OK in version 0.8.3, available now.
