### ISSUE TITLE
Custom config vs pre-defined lights

### ISSUE THREAD

**Issue by JamzTheMan** [PhilippeKr/TorchLight#12]
First, thanks for picking up the "torch" and continuing this simple module 👍 

It would be nice if, as the GM on the configuration UI, let me just define the color and Foundry "effect" to apply vs the drop downs? The drop downs are nice for most who don't want to play with it but I find most of the color choices either to mute or to harsh for my scenes.

Hopefully this isn't a big ask?

**Comment by PhilippeKr** [comment]
I have created a custom setting for each type of light, check out version 0.9.0.

**Comment by JamzTheMan** [comment]
Awesome, going to check it out now!
