### ISSUE TITLE
"Required field lightAlpha not present in Token".

### ISSUE THREAD

**Issue by Diplomatie** [PhilippeKr/TorchLight#2]
Getting error "Required field lightAlpha not present in Token".
First time using this module. 

I can activate by clicking and the light works. cool. but when I try to turn it off, I get this error.
After that, no matter how many times I click, the light animation leaves, but the light effect (vision) stays and I have to remove it manually.

It does the same for all my tokens: 
- My custom ones
- Imported ones with plutonium
- Imported ones from DndBeyond)

Do I need an other module for this one to work ? Could an other module break this one ?

**Comment by PhilippeKr** [comment]
Thanks for the report, it was a simple bug in my implementation, and corrected in version 0.6.5.
