### ISSUE TITLE
Cannot turn off lights.

### ISSUE THREAD

**Issue by FrozenSCV** [PhilippeKr/TorchLight#29]
When trying to turn of a light it gives the following error 
Tokendata light color "16777215" is not a valid hexadecimal color string. 

This happens when trying to turn off any light. It will properly switch lights if other lights are clicked, but will not remove them.

**Comment by vanderleitelesjr** [comment]
Probably an incompatibility with the light system changes of 0.8.x, I just updated to the new stable version (0.8.6) and started to experience the same issue. Also when turning on the light the brightness is way to high in the player view (brightness seems normal on GM side though).

**Comment by lukejpreston** [comment]
I am seeing this as well on the stable version of 0.8.x in Foundry

**Comment by CommanderAlex98** [comment]
Same her after update to 0.8.x. Pls fix. It is a nice module.

**Comment by shopstein** [comment]
I have the same problem too. Is this module still supported? I hope so, it's great.

**Comment by PhilippeKr** [comment]
Hi, Unfortunately, while I wanted to experiment with the development within foundry and had some available leisure at that point in time, it is no longer the case. Moreover, I did not foreseen the amount of requests to expand the module. I have tried to follow up at start, but it has become quite bloated and therefore difficult in particular to test. Neither did I foreseen that a change of version in Foundry would require me to update the module, especially when the documentation about the update is not that precise. So I'm sorry, but I won't be able to maintain the module anymore, if anyone wants to take it over, it will be with my full blessing.

**Comment by shopstein** [comment]
That's absolut understandable. Maybe I will have a look at it in the next days.

**Comment by cs96and** [comment]
I might be willing to get this in a working state for 0.8.x, but not to take on full ownership and add any outstanding feature requests.

@PhilippeKr, would you be willing to do a release if I submitted a pull request with 0.8.x fixes?

**Comment by PhilippeKr** [comment]
This is a great offer, thanks, as there are quite a few people requesting it here and on GitHub. The only thing I must confess is that I'm really a noob at all that, it was mostly a project to keep some of my skills from degrading. So no worries about doing the release, but you might have to take me through it step by step though.

Alternatively, I'm not using GitHub for anything else than this project, so I will gladly give you my user/password if you want to maintain it here, or if you just need them for the final release, let me know.

**Comment by cs96and** [comment]
> So no worries about doing the release, but you might have to take me through it step by step though.

I'm slightly confused by this statement, as you have already made several releases, so you must know how to do them already!

**Comment by PhilippeKr** [comment]
I did them, but in a simple way, straightforward and without taking in pull requests, and so on, that's all. And that was a few months ago, so I might need some refreshing. I have quite a bit of development behind me, but most of it was a long time ago professionally, so I have a few reflexes, but I get lost fairly quickly in the intricacies of GitHub.

**Comment by cs96and** [comment]
The pull request part is easy.  Once you are happy with it you just accept it and merge in the changes.  Then you just do the release you you normally would.  I'm not sure how you built your previous releases though, so I can't help you with that.

**Comment by PhilippeKr** [comment]
That's fine, I'm sure I'll be able to figure it out again.

**Comment by cs96and** [comment]
Pull request submitted

**Comment by PhilippeKr** [comment]
Thanks, I'm trying to shake the rust from all that, working on it this weekend to get it back into the official modules, I'll let you know when I'm done.
