### ISSUE TITLE
Torch is pulsing to much

### ISSUE THREAD

**Issue by talasek** [PhilippeKr/TorchLight#3]
everytime a player toggles torch - the animation type switches to torch - which is pulsing quite heavily.
For the eye it is better to use something like smoke Patch.

**Comment by talasek** [comment]
Possible solution: allow more animation types in the torch light configuration or store the token light animation type.
Or allow playersetting for light, lantern and torch.

**Comment by cs96and** [comment]
All the animations are a bit too much for me.  I would much prefer something a bit more subtle.  It would be good if the standard token light settings were available for all three light types.

**Comment by PhilippeKr** [comment]
This is supposed to be a simple module, not something to set all the parameters for light sources and, as far as I know, the smoke patch comes from yet another module and I think I'd rather not introduce too many depedencies.

That being said, it's not too hard to either add more light types for the three types of light, or to modify the existing parameters.

If you tell me some are useless (which I can believe), I will remove them, and if you give me the parameters that you would like for the various types of light I will be happy to put them in the module, with my thanks.

**Comment by Red5Phil** [comment]
I'd prefer to just have the correct light radius set per selection, without animations. I have a player who is prone to migraines and the torch light animation is too much for them.

**Comment by talasek** [comment]
@Red5Phil  You could co to lighttourch.js locally and swap the animationtype from "torch" to "none". I've sitched manually to "SecretFireSmoke Patch".
@PhilippeKr maybe a simple picker for the animationtype would help?

**Comment by PhilippeKr** [comment]
The first thing that I will do is create a Type 0 without animation, you are right, some of the animations are just too much.

After that, I will see about a picker, but an animation picker would also require an animation speed picker, etc.

**Comment by PhilippeKr** [comment]
I have created a Type 0 without effect, that should correct some of the problems, but a picker is a bit beyond what I can do at the time, I need a bit more thinking about it. 

I will close this issue because it has diverged a bit too much, but I will happily discuss more specific issues in other topics.

**Comment by cs96and** [comment]
This is much better now thanks.  However could I suggest one minor tweak?  Can you turn down the colour intensity please?  I find that 0.3 or 0.35 is OK for the Light spell, and 0.5 for the lantern and torch looks much better.
