### ISSUE TITLE
Update for Foundry 0.8.x?

### ISSUE THREAD

**Issue by PhluXx1** [PhilippeKr/TorchLight#31]
Thanks you for this amazing module it's used all the time by my party.

Do you have any plans to update this module for Foundry version 0.8.6? If so do you have a timefram? It currently doesn't work and is very much missed.

**Comment by PhilippeKr** [comment]
Hi, Unfortunately, while I wanted to experiment with the development within foundry and had some available leisure at that point in time, it is no longer the case. Moreover, I did not foreseen the amount of requests to expand the module. I have tried to follow up at start, but it has become quite bloated and therefore difficult in particular to test. Neither did I foreseen that a change of version in Foundry would require me to update the module, especially when the documentation about the update is not that precise. So I'm sorry, but I won't be able to maintain the module anymore, if anyone wants to take it over, it will be with my full blessing.
