### ISSUE TITLE
Stuck on version 0.6.5

### ISSUE THREAD

**Issue by notrealdan** [PhilippeKr/TorchLight#4]
The module.json file in github says it's version 0.7.0, but it points to torchlight.zip, which is version 0.6.5 (according to the module.json file within).  The result is that Foundry always thinks there's an update for this module, and re-installs the older version.  I think the zip file on github needs to be replaced with the latest version.

**Comment by PhilippeKr** [comment]
Thanks, I saw  that afterwards, as I'm not an expert in any of this. It is corrected in the later versions.
