### ISSUE TITLE
Suggestion: Make it configurable per token?

### ISSUE THREAD

**Issue by GambetTV** [PhilippeKr/TorchLight#9]
I really like the module, but the thing that keeps me from using it is that it permanently puts 3 lights on all tokens, all configured in the same exact way. I would love to see this have an option to toggle it to an expansion of the Vision tab in Token Configuration. That way each token can have separate light sources configured in different ways depending on their specific needs.

This would probably dramatically expand the usefulness of the module too, considering all the Light Animation Types available these days. Instead of simply having 3 different lights, you could set up monsters to trail a fog cloud, or set it up for a dome shield effect, and all sorts of other things people could come up with.

Just my two cents!

**Comment by talasek** [comment]
I would appreciate that as well - especially because the torch animation needs to be configurable - the animation pulses to fast. Actually i would like to set the smoke patch animation for the torch - reducing the animation noise on the field.

**Comment by PhilippeKr** [comment]
I think this goes way beyond the intent of this simple module. There are other much more complex modules that allow you to do this per token, but it would require so much configuration that actually simple use by DMs and players would be hampered.
